<?php

/**
 * پارامترهای استخراج‌شده از فرم مبایعه‌نامه ۱۲۵ (نقطه‌چین‌ها)
 */
return [
    'fields' => [
        ['key' => 'seller_name', 'label' => 'نام و نام خانوادگی فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_father', 'label' => 'نام پدر فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_id_number', 'label' => 'شماره شناسنامه فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_id_issue_place', 'label' => 'محل صدور شناسنامه فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_national_id', 'label' => 'کد ملی فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_birth_date', 'label' => 'تاریخ تولد فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_address', 'label' => 'آدرس فروشنده', 'group' => 'فروشنده'],
        ['key' => 'seller_phone', 'label' => 'تلفن فروشنده', 'group' => 'فروشنده'],
        ['key' => 'buyer_name', 'label' => 'نام و نام خانوادگی خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_father', 'label' => 'نام پدر خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_id_number', 'label' => 'شماره شناسنامه خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_id_issue_place', 'label' => 'محل صدور شناسنامه خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_national_id', 'label' => 'کد ملی خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_birth_date', 'label' => 'تاریخ تولد خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_address', 'label' => 'آدرس خریدار', 'group' => 'خریدار'],
        ['key' => 'buyer_phone', 'label' => 'تلفن خریدار', 'group' => 'خریدار'],
        ['key' => 'property_share', 'label' => 'دانگ انتقالی', 'group' => 'ملک'],
        ['key' => 'property_type', 'label' => 'نوع ملک (آپارتمان/ویلایی/...)', 'group' => 'ملک'],
        ['key' => 'registry_plate', 'label' => 'پلاک ثبتی', 'group' => 'ملک'],
        ['key' => 'registry_sub', 'label' => 'فرعی از', 'group' => 'ملک'],
        ['key' => 'registry_main', 'label' => 'اصلی قطعه', 'group' => 'ملک'],
        ['key' => 'registry_section', 'label' => 'بخش ثبتی', 'group' => 'ملک'],
        ['key' => 'registry_office', 'label' => 'حوزه ثبتی', 'group' => 'ملک'],
        ['key' => 'property_area', 'label' => 'مساحت (متر مربع)', 'group' => 'ملک'],
        ['key' => 'deed_serial', 'label' => 'شماره سریال سند', 'group' => 'ملک'],
        ['key' => 'deed_page', 'label' => 'صفحه سند', 'group' => 'ملک'],
        ['key' => 'deed_book', 'label' => 'دفتر سند', 'group' => 'ملک'],
        ['key' => 'deed_owner_name', 'label' => 'نام مندرج در سند', 'group' => 'ملک'],
        ['key' => 'property_address', 'label' => 'نشانی ملک', 'group' => 'ملک'],
        ['key' => 'utilities', 'label' => 'حقوق اشتراک (آب/برق/گاز/تلفن/...)', 'group' => 'ملک'],
        ['key' => 'total_price_number', 'label' => 'ثمن به عدد (ریال)', 'group' => 'ثمن'],
        ['key' => 'total_price_words', 'label' => 'ثمن به حروف', 'group' => 'ثمن'],
        ['key' => 'paid_amount_number', 'label' => 'مبلغ پرداختی به عدد', 'group' => 'ثمن'],
        ['key' => 'paid_amount_words', 'label' => 'مبلغ پرداختی به حروف', 'group' => 'ثمن'],
        ['key' => 'payment_method', 'label' => 'نحوه پرداخت (نقد/چک)', 'group' => 'ثمن'],
        ['key' => 'remaining_price', 'label' => 'باقیمانده ثمن', 'group' => 'ثمن'],
        ['key' => 'deed_date', 'label' => 'تاریخ تنظیم سند (روز/ماه/سال)', 'group' => 'سند'],
        ['key' => 'notary_office', 'label' => 'شماره دفتر اسناد رسمی', 'group' => 'سند'],
        ['key' => 'delivery_date', 'label' => 'تاریخ تحویل ملک', 'group' => 'تحویل'],
        ['key' => 'penalty_non_transfer', 'label' => 'خسارت عدم انتقال (ریال)', 'group' => 'جریمه'],
        ['key' => 'penalty_breach_seller', 'label' => 'خسارت تخلف فروشنده', 'group' => 'جریمه'],
        ['key' => 'penalty_breach_buyer', 'label' => 'خسارت تخلف خریدار', 'group' => 'جریمه'],
        ['key' => 'registry_fee_bearer', 'label' => 'هزینه حق الثبت بر عهده', 'group' => 'سایر'],
        ['key' => 'commission_receipt_1', 'label' => 'قبض کمیسیون شماره ۱', 'group' => 'کمیسیون'],
        ['key' => 'commission_receipt_2', 'label' => 'قبض کمیسیون شماره ۲', 'group' => 'کمیسیون'],
        ['key' => 'contract_date', 'label' => 'تاریخ قرارداد', 'group' => 'سایر'],
        ['key' => 'consultant_license', 'label' => 'شماره پروانه مشاور', 'group' => 'مشاور'],
        ['key' => 'consultant_office_address', 'label' => 'نشانی دفتر مشاور', 'group' => 'مشاور'],
        ['key' => 'register_page', 'label' => 'صفحه ثبت دفتر', 'group' => 'ثبت'],
        ['key' => 'register_volume', 'label' => 'جلد ثبت', 'group' => 'ثبت'],
        ['key' => 'register_number', 'label' => 'شماره ثبت', 'group' => 'ثبت'],
        ['key' => 'serial_number', 'label' => 'شماره سریال', 'group' => 'ثبت'],
        ['key' => 'legal_expert_name', 'label' => 'نام کارشناس حقوقی', 'group' => 'امضا'],
        ['key' => 'witness_name', 'label' => 'نام شاهد', 'group' => 'امضا'],
        ['key' => 'office_name', 'label' => 'نام دفتر املاک (خودکار)', 'group' => 'سیستم', 'auto' => true],
        ['key' => 'property_code', 'label' => 'کد ملک (خودکار)', 'group' => 'سیستم', 'auto' => true],
        ['key' => 'property_price', 'label' => 'قیمت ملک (خودکار)', 'group' => 'سیستم', 'auto' => true],
        ['key' => 'today_jalali', 'label' => 'تاریخ امروز شمسی (خودکار)', 'group' => 'سیستم', 'auto' => true],
    ],
];
