import type { LucideIcon } from 'lucide-react'
import {
  Building2, Kanban, Calculator, Globe, FileText, Scale, Handshake,
  Sparkles, Smartphone, QrCode, Bot, BarChart3, Camera, MapPin, Home,
  Wallet, Users, Shield, Zap, Calendar, Cloud, Headphones,
} from 'lucide-react'

export interface KeywordLandingBenefit {
  icon: LucideIcon
  title: string
  desc: string
}

export interface KeywordLandingConfig {
  slug: string
  keyword: string
  title: string
  metaDescription: string
  keywords: string
  heroBadge: string
  heroTitle: string
  heroSubtitle: string
  heroImage: string
  accent: string
  glow: string
  painTitle: string
  painPoints: string[]
  benefits: KeywordLandingBenefit[]
  steps: { title: string; desc: string }[]
  faq: { q: string; a: string }[]
  ctaTitle: string
  ctaSubtitle: string
  relatedSlugs: string[]
}

const IMG = {
  filing: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1400&q=80',
  crm: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=80',
  accounting: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&q=80',
  tour: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1400&q=80',
  contract: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1400&q=80',
  office: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1400&q=80',
  brand: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1400&q=80',
}

export const KEYWORD_LANDINGS: KeywordLandingConfig[] = [
  {
    slug: 'filing-amlak',
    keyword: 'فایلینگ املاک',
    title: 'فایلینگ املاک بدون اکسل و کاغذ — پوشه',
    metaDescription: 'فایلینگ املاک واقعی یعنی همه فایل‌ها یکجا، با عکس، QR و جستجوی سریع. ۴۸ ساعت رایگان پوشه.',
    keywords: 'فایلینگ املاک, نرم افزار فایلینگ املاک, ثبت ملک, پوشه',
    heroBadge: 'دیگه فایل گم نمی‌شه',
    heroTitle: 'فایلینگ املاک؛ همون جایی که همه فایل‌ها سر جاشونن',
    heroSubtitle: 'نه پوشه کاغذی، نه اکسل قاطی‌پاتی. هر ملک با عکس، مالک، قیمت و QR — توی چند ثانیه پیداش کن.',
    heroImage: IMG.filing,
    accent: 'from-emerald-500 to-teal-600',
    glow: 'bg-emerald-500/20',
    painTitle: 'صداش رو می‌شناسی؟',
    painPoints: [
      '«فایلش کجاست؟» — و نیم ساعت دنبال عکس می‌گردی',
      'هر مشاور نسخه خودش از فایل رو داره',
      'دیوار می‌خواد عکس تمیز، تو گالری گوشی قاطیه',
      'مشتری زنگ می‌زنه، نمی‌دونی کدوم فایل رو فرستادی',
    ],
    benefits: [
      { icon: Building2, title: '۳۰+ فیلد حرفه‌ای', desc: 'متراژ، سند، جهت، امکانات — همه‌چیز برای فروش' },
      { icon: QrCode, title: 'QR برای هر فایل', desc: 'اسکن کن، همون فایل باز می‌شه' },
      { icon: Sparkles, title: 'کپی آگهی یک کلیک', desc: 'متن آماده دیوار و شبکه‌ها' },
      { icon: Globe, title: 'لینک عمومی ملک', desc: 'بفرست برای مشتری، بدون واتساپ شلوغ' },
    ],
    steps: [
      { title: 'ثبت‌نام رایگان', desc: 'ایمیل و رمز — بدون پیچک‌پیچ' },
      { title: 'اولین فایل رو بزن', desc: 'عکس بنداز، فیلدها پر کن' },
      { title: 'بفرست و بفروش', desc: 'QR، لینک، واتساپ — هر جور دوست داری' },
    ],
    faq: [
      { q: 'از اکسل بهتره واقعاً؟', a: 'وقتی ۵۰۰ فایل داری و ۳ مشاور همزمان کار می‌کنن، بله. خیلی.' },
      { q: 'عکس‌ها کجا ذخیره می‌شن؟', a: 'ابر امن — نه گوشی مشاور، نه لپ‌تاپ شخصی.' },
    ],
    ctaTitle: 'همین الان فایلینگ رو درست کن',
    ctaSubtitle: '۴۸ ساعت رایگان — بدون کارت بانکی',
    relatedSlugs: ['crm-amlak', 'virtual-tour-amlak', 'posheh-software'],
  },
  {
    slug: 'crm-amlak',
    keyword: 'CRM املاک',
    title: 'CRM املاک که مشتری رو گم نکنه — پوشه',
    metaDescription: 'CRM املاک پوشه: مشتری، بازدید، کانبان معامله و Match هوشمند. خودمونی و ساده، نه سخت و کتابی.',
    keywords: 'CRM املاک, برنامه CRM املاک, مدیریت مشتری املاک, پوشه',
    heroBadge: 'مشتری گم نشه',
    heroTitle: 'CRM املاک؛ وقتی «فردا زنگ می‌زنم» واقعاً یادت می‌مونه',
    heroSubtitle: 'کانبان معامله، یادآور بازدید، تطبیق ملک و مشتری — همه توی یک پنل که مشاورها دوستش دارن.',
    heroImage: IMG.crm,
    accent: 'from-amber-500 to-orange-600',
    glow: 'bg-amber-500/20',
    painTitle: 'این‌ها رو دیدی؟',
    painPoints: [
      'مشتری خوب از دست رفت چون کسی follow-up نکرد',
      'نمی‌دونی معامله کجای پایپ‌لاینه',
      'بازدید رفت، یادداشت نشد، فراموش شد',
      'هر مشاور لیست مشتری خودش رو داره',
    ],
    benefits: [
      { icon: Kanban, title: 'کانبان معامله', desc: 'بکش ببر — از تماس تا قرارداد' },
      { icon: Users, title: 'پروفایل مشتری کامل', desc: 'بودجه، منطقه، تاریخچه بازدید' },
      { icon: Zap, title: 'Match هوشمند', desc: 'سیستم خودش ملک مناسب رو پیشنهاد می‌ده' },
      { icon: Smartphone, title: 'یادآور SMS بازدید', desc: 'مشتری و مشاور هر دو یادشون می‌مونه' },
    ],
    steps: [
      { title: 'مشتری رو ثبت کن', desc: 'شماره، بودجه، خواسته' },
      { title: 'ملک Match بزن', desc: 'پیشنهاد خودکار از فایلینگ' },
      { title: 'معامله رو ببر جلو', desc: 'کانبان تا بستن قرارداد' },
    ],
    faq: [
      { q: 'با فایلینگ یکیه؟', a: 'کنار هم کار می‌کنن — فایل و مشتری همیشه لینک هستن.' },
      { q: 'چند مشاور همزمان؟', a: 'بسته به پلن — از ۱ تا ۱۰ نفر.' },
    ],
    ctaTitle: 'CRM رو امتحان کن — رایگان',
    ctaSubtitle: 'همون روزی که شروع کنی، مشتری گم نمی‌شه',
    relatedSlugs: ['filing-amlak', 'accounting-amlak', 'posheh-software'],
  },
  {
    slug: 'accounting-amlak',
    keyword: 'حسابداری املاک',
    title: 'حسابداری املاک بدون دفتر حساب دستی — پوشه',
    metaDescription: 'حسابداری املاک و کمیسیون مشاوران توی پوشه. درآمد، هزینه، گزارش — شفاف و ساده.',
    keywords: 'حسابداری املاک, نرم افزار حسابداری املاک, کمیسیون مشاور, پوشه',
    heroBadge: 'پول قاطی نشه',
    heroTitle: 'حسابداری املاک؛ آخر ماه استرس نداشته باش',
    heroSubtitle: 'درآمد دفتر، هزینه‌ها، کمیسیون هر مشاور — یکجا ببین چی میره کجا.',
    heroImage: IMG.accounting,
    accent: 'from-cyan-500 to-blue-600',
    glow: 'bg-cyan-500/20',
    painTitle: 'آشنایی؟',
    painPoints: [
      'کمیسیون مشاورها دستی حساب می‌شه',
      'نمی‌دونی این ماه دفتر چقدر سود کرد',
      'رسید و فاکتور پخش — آخر ماه جمع می‌کنی',
      'مدیر فقط از مشاور می‌پرسه «چقدر بستی؟»',
    ],
    benefits: [
      { icon: Calculator, title: 'درآمد و هزینه', desc: 'هر تراکنش ثبت — گزارش لحظه‌ای' },
      { icon: Wallet, title: 'کمیسیون خودکار', desc: 'بر اساس معامله و قرارداد' },
      { icon: BarChart3, title: 'گزارش KPI', desc: 'عملکرد هر مشاور شفاف' },
      { icon: FileText, title: 'خروجی برای حسابدار', desc: 'Excel و PDF آماده' },
    ],
    steps: [
      { title: 'معامله ثبت کن', desc: 'از CRM یا قرارداد' },
      { title: 'کمیسیون تقسیم شه', desc: 'قوانین دفتر رو یکبار بزن' },
      { title: 'گزارش بگیر', desc: 'ماهانه، فصلی، هر چی بخوای' },
    ],
    faq: [
      { q: 'حسابدار خارجی هم می‌فهمه؟', a: 'خروجی استاندارد داری — راحت تحویل بده.' },
      { q: 'با قراردادها وصله؟', a: 'آره — مبایعه‌نامه و اجاره‌نامه همون اکوسیستمه.' },
    ],
    ctaTitle: 'حسابداری رو ساده کن',
    ctaSubtitle: '۴۸ ساعت رایگان — ببین آخر ماه چقدر راحت می‌شه',
    relatedSlugs: ['crm-amlak', 'mubayaeh-amlak', 'posheh-software'],
  },
  {
    slug: 'accounting-software-amlak',
    keyword: 'نرم افزار حسابداری املاک',
    title: 'نرم افزار حسابداری املاک — پوشه',
    metaDescription: 'نرم افزار حسابداری املاک مخصوص دفتر مشاور — نه حسابداری عمومی که گیجت کنه.',
    keywords: 'نرم افزار حسابداری املاک, حسابداری املاک, پوشه',
    heroBadge: 'مخصوص املاک',
    heroTitle: 'نرم افزار حسابداری املاک که زبان دفتر رو حرف بزنه',
    heroSubtitle: 'کمیسیون، قرارداد، مشاور — نه فقط «بدهکار و بستانکار» برای شرکت تولیدی.',
    heroImage: IMG.accounting,
    accent: 'from-sky-500 to-indigo-600',
    glow: 'bg-sky-500/20',
    painTitle: 'نرم‌افزار عمومی خسته‌ت کرده؟',
    painPoints: [
      'حسابداری عمومی نمی‌فهمه «کمیسیون مشاور» چیه',
      'هر معامله دستی وارد می‌کنی',
      'با فایلینگ و CRM جداست',
      'آموزشش طولانیه',
    ],
    benefits: [
      { icon: Calculator, title: 'طراحی برای املاک', desc: 'فیلدهای همون کاری که می‌کنی' },
      { icon: Handshake, title: 'یکپارچه با معامله', desc: 'از CRM تا پول — یک خط' },
      { icon: Shield, title: 'داده جدا برای هر دفتر', desc: 'امنیت و حریم خصوصی' },
      { icon: Zap, title: 'راه‌اندازی سریع', desc: 'کمتر از ۳ دقیقه' },
    ],
    steps: [
      { title: 'ثبت‌نام', desc: 'رایگان شروع کن' },
      { title: 'تنظیم کمیسیون', desc: 'یکبار قوانین دفتر' },
      { title: 'روزانه ثبت کن', desc: 'خودش جمع می‌کنه' },
    ],
    faq: [
      { q: 'چقدر با حسابداری عمومی متفاوته؟', a: 'از اول برای دفتر املاک طراحی شده — نه تطبیق اجباری.' },
    ],
    ctaTitle: 'نرم‌افزار درست رو انتخاب کن',
    ctaSubtitle: 'پوشه — فایلینگ + CRM + حسابداری یکجا',
    relatedSlugs: ['accounting-amlak', 'filing-amlak'],
  },
  {
    slug: 'crm-app-amlak',
    keyword: 'برنامه CRM املاک',
    title: 'برنامه CRM املاک برای موبایل و وب — پوشه',
    metaDescription: 'برنامه CRM املاک روی موبایل، اندروید و وب. مشتری و معامله همیشه دستته.',
    keywords: 'برنامه CRM املاک, CRM املاک, اپلیکیشن مشاور املاک, پوشه',
    heroBadge: 'موبایل + وب',
    heroTitle: 'برنامه CRM املاک که تو ماشین هم جواب بده',
    heroSubtitle: 'بازدید زدنی، مشتری زنگ زد — از گوشی همه‌چیز رو ببین و آپدیت کن.',
    heroImage: IMG.crm,
    accent: 'from-violet-500 to-purple-600',
    glow: 'bg-violet-500/20',
    painTitle: 'بدون اپ چی می‌شه؟',
    painPoints: [
      'بازدید هستی، فایل رو نداری',
      'مشتری زنگ می‌زنه، باید برگردی دفتر',
      'یادداشت روی کاغذ گم می‌شه',
      'واتساپ شلوغ — کدوم فایل بود؟',
    ],
    benefits: [
      { icon: Smartphone, title: 'وب + اندروید', desc: 'هر دستگاهی داری' },
      { icon: Kanban, title: 'کانبان سریع', desc: 'وضعیت معامله یک ضرب' },
      { icon: MapPin, title: 'بازدید و تقویم', desc: 'شمسی، یادآور SMS' },
      { icon: Bot, title: 'ربات تلگرام', desc: 'پاسخ خودکار به مشتری' },
    ],
    steps: [
      { title: 'دانلود یا وب', desc: 'همون اکانت' },
      { title: 'مشتری اضافه', desc: 'تو راه بازدید' },
      { title: 'بستن معامله', desc: 'از موبایل تا قرارداد' },
    ],
    faq: [
      { q: 'آفلاین کار می‌کنه؟', a: 'وب همیشه آنلاین — داده ابری sync می‌شه.' },
    ],
    ctaTitle: 'برنامه رو نصب کن — رایگان',
    ctaSubtitle: '۴۸ ساعت تست کامل',
    relatedSlugs: ['crm-amlak', 'posheh-software'],
  },
  {
    slug: 'virtual-tour-amlak',
    keyword: 'تور مجازی املاک',
    title: 'تور مجازی املاک حرفه‌ای — پوشه',
    metaDescription: 'تور مجازی املاک با ۳۶۰ و اسمارت‌واک، موزیک، QR و embed. بساز، بفرست، بفروش.',
    keywords: 'تور مجازی املاک, بازدید مجازی املاک, املاک مجازی, تور ۳۶۰, پوشه',
    heroBadge: 'بازدید بی‌هدف کم شه',
    heroTitle: 'تور مجازی املاک — مشتری قبل از راه‌اندازی می‌فهمه می‌خواد یا نه',
    heroSubtitle: '۳۶۰، اسمارت‌واک، فلش بین اتاق‌ها، موزیک — تور حرفه‌ای بدون تیم فیلمبرداری.',
    heroImage: IMG.tour,
    accent: 'from-teal-500 to-emerald-600',
    glow: 'bg-teal-500/20',
    painTitle: 'بازدید حضوری خسته‌کننده؟',
    painPoints: [
      '۱۰ بازدید، ۸‌ش بی‌نتیجه',
      'مشتری دوره — فقط می‌خواد «ببینم»',
      'عکس توی واتساپ کیفیتش رفته',
      'رقبا تور دارن، تو اسکرین‌شات می‌فرستی',
    ],
    benefits: [
      { icon: Camera, title: '۳۶۰ + اسمارت‌واک', desc: 'هر نوع فضا' },
      { icon: Globe, title: 'لینک و embed', desc: 'سایت دفتر، دیوار، واتساپ' },
      { icon: Sparkles, title: 'موزیک و برند', desc: 'تور مثل آژانس حرفه‌ای' },
      { icon: BarChart3, title: 'آنالیتیکس کلیک', desc: 'ببین کی دیده' },
    ],
    steps: [
      { title: 'فایل رو ثبت کن', desc: 'از فایلینگ' },
      { title: 'تور بساز', desc: 'چند صحنه، اتصال، publish' },
      { title: 'لینک بفرست', desc: 'مشتری از خونه ببینه' },
    ],
    faq: [
      { q: 'سخت نیست؟', a: 'خودت عکس بگیر، توی پنل بچین — راهنما داخل نرم‌افزار.' },
      { q: 'روی موبایل خوبه؟', a: 'آره — مخصوص اندروید و iOS بهینه شده.' },
    ],
    ctaTitle: 'اولین تور مجازی رو بساز',
    ctaSubtitle: '۴۸ ساعت رایگان — فایلینگ + تور یکجا',
    relatedSlugs: ['virtual-tour-property', 'virtual-visit-amlak', 'filing-amlak'],
  },
  {
    slug: 'virtual-tour-property',
    keyword: 'تور مجازی ملک',
    title: 'تور مجازی ملک — برای هر آپارتمان و ویلا',
    metaDescription: 'تور مجازی ملک: مشتری قبل از بازدید حضوری ملک رو قدم‌به‌قدم ببینه.',
    keywords: 'تور مجازی ملک, بازدید ملک مجازی, پوشه',
    heroBadge: 'هر ملک یک تور',
    heroTitle: 'تور مجازی ملک — انگار خودش راه رفته تو ملک',
    heroSubtitle: 'آپارتمان، ویلا، مغازه — هر فایلی می‌تونه تور داشته باشه. یک لینک، همه جا.',
    heroImage: IMG.tour,
    accent: 'from-emerald-400 to-cyan-600',
    glow: 'bg-emerald-500/20',
    painTitle: 'چرا مهمه؟',
    painPoints: [
      'مشتری از شهر دیگه — نمی‌تونه هر روز بیاد',
      'عکس ۱۰ تا کافی نیست — فضا رو نمی‌فهمه',
      'بازدید حضوری وقت مشاور رو می‌گیره',
      'فایل لوکس بدون تور — حس نمی‌کنه',
    ],
    benefits: [
      { icon: Home, title: 'هر نوع ملک', desc: 'مسکونی، تجاری، اداری' },
      { icon: Camera, title: 'چند صحنه', desc: 'اتاق، پذیرایی، نما' },
      { icon: QrCode, title: 'QR روی آگهی', desc: 'اسکن = تور' },
      { icon: FileText, title: 'کنار فایلینگ', desc: 'همون پنل' },
    ],
    steps: [
      { title: 'ملک ثبت', desc: 'عکس‌ها آماده' },
      { title: 'تور بساز', desc: '۵ دقیقه' },
      { title: 'بفرست', desc: 'واتساپ یا لینک' },
    ],
    faq: [
      { q: 'چند صحنه لازمه؟', a: 'هر چقدر بخوای — از ۲ تا ۲۰.' },
    ],
    ctaTitle: 'برای ملک بعدی تور بساز',
    ctaSubtitle: 'رایگان شروع کن',
    relatedSlugs: ['virtual-tour-amlak', 'virtual-property-visit'],
  },
  {
    slug: 'real-estate-law',
    keyword: 'حقوق املاک',
    title: 'حقوق املاک و قرارداد دیجیتال — پوشه',
    metaDescription: 'حقوق املاک عملی: مبایعه‌نامه و اجاره‌نامه دیجیتال با قالب استاندارد در پوشه.',
    keywords: 'حقوق املاک, قرارداد املاک, پوشه',
    heroBadge: 'قرارداد درست',
    heroTitle: 'حقوق املاک — وقتی قرارداد شُل نباشه',
    heroSubtitle: 'مبایعه‌نامه و اجاره‌نامه با قالب معتبر، PDF فارسی و تاریخ شمسی — بدون ورد دستی.',
    heroImage: IMG.contract,
    accent: 'from-slate-500 to-zinc-700',
    glow: 'bg-slate-500/20',
    painTitle: 'قرارداد دستی؟',
    painPoints: [
      'هر بار ورد رو از اول پر می‌کنی',
      'تاریخ میلادی اشتباه می‌خوره',
      'نسخه‌ها قاطی — کدوم امضا شد؟',
      'مشاور جدید نمی‌دونه قالب کجاست',
    ],
    benefits: [
      { icon: Scale, title: 'قالب استاندارد', desc: 'فرم ۱۲۵ و اجاره‌نامه' },
      { icon: FileText, title: 'PDF و Word', desc: 'خروجی آماده چاپ' },
      { icon: Shield, title: 'اطلاعات از فایل', desc: 'ملک و طرفین خودکار' },
      { icon: Users, title: 'آرشیو دفتر', desc: 'همه قراردادها یکجا' },
    ],
    steps: [
      { title: 'فایل و مشتری', desc: 'قبلاً توی سیستم' },
      { title: 'قرارداد بزن', desc: 'پر شد خودکار' },
      { title: 'چاپ و امضا', desc: 'PDF بگیر' },
    ],
    faq: [
      { q: 'با فایلینگ یکیه؟', a: 'آره — اطلاعات ملک و مالک همونجاست.' },
    ],
    ctaTitle: 'قرارداد دیجیتال رو امتحان کن',
    ctaSubtitle: '۴۸ ساعت رایگان',
    relatedSlugs: ['mubayaeh-amlak', 'ejareh-amlak'],
  },
  {
    slug: 'mubayaeh-amlak',
    keyword: 'مبایعه نامه املاک',
    title: 'مبایعه نامه املاک دیجیتال — پوشه',
    metaDescription: 'مبایعه نامه املاک آنلاین — فرم ۱۲۵، PDF فارسی، تاریخ شمسی.',
    keywords: 'مبایعه نامه املاک, مبایعه نامه, فرم 125, پوشه',
    heroBadge: 'فرم ۱۲۵ آماده',
    heroTitle: 'مبایعه‌نامه املاک — بدون کپی‌پیست از فایل قبلی',
    heroSubtitle: 'اطلاعات ملک و خریدار از سیستم می‌آد. چاپ بگیر، امضا کن، آرشیو کن.',
    heroImage: IMG.contract,
    accent: 'from-rose-500 to-red-600',
    glow: 'bg-rose-500/20',
    painTitle: 'دستی خسته‌ت کرد؟',
    painPoints: [
      'هر مبایعه‌نامه ۲۰ دقیقه تایپ',
      'آدرس و متراژ اشتباه کپی می‌شه',
      'نسخه فیزیکی گم می‌شه',
      'حسابداری جدا — دوباره‌کاری',
    ],
    benefits: [
      { icon: FileText, title: 'قالب فرم ۱۲۵', desc: 'مطابق عرف دفتر' },
      { icon: Calculator, title: 'وصل به حسابداری', desc: 'معامله ثبت می‌شه' },
      { icon: Building2, title: 'از روی فایل', desc: 'کد، آدرس، متراژ' },
      { icon: Sparkles, title: 'تاریخ شمسی', desc: 'خودکار' },
    ],
    steps: [
      { title: 'معامله در CRM', desc: 'یا مستقیم از فایل' },
      { title: 'مبایعه‌نامه', desc: 'یک کلیک PDF' },
      { title: 'آرشیو', desc: 'همیشه پیداش کن' },
    ],
    faq: [
      { q: 'چاپ قانونیه؟', a: 'قالب استاندارد — مثل ورد دفتر، با داده درست.' },
    ],
    ctaTitle: 'مبایعه‌نامه رو دیجیتال کن',
    ctaSubtitle: 'رایگان تست کن',
    relatedSlugs: ['ejareh-amlak', 'real-estate-law'],
  },
  {
    slug: 'ejareh-amlak',
    keyword: 'اجاره نامه املاک',
    title: 'اجاره نامه املاک آنلاین — پوشه',
    metaDescription: 'اجاره نامه املاک با قالب حرفه‌ای، PDF و اتصال به فایل و مشتری.',
    keywords: 'اجاره نامه املاک, اجاره نامه, پوشه',
    heroBadge: 'اجاره بدون استرس',
    heroTitle: 'اجاره‌نامه املاک — مبلغ و تاریخ درست، هر بار',
    heroSubtitle: 'موجر و مستأجر از سیستم، شرایط و ضمانت — PDF آماده.',
    heroImage: IMG.contract,
    accent: 'from-indigo-500 to-blue-600',
    glow: 'bg-indigo-500/20',
    painTitle: 'اجاره پر تکراره',
    painPoints: [
      'هر اجاره دوباره تایپ',
      'شرایط ضمانت فراموش می‌شه',
      'تمدید قرارداد — فایل قدیمی کجاست؟',
      'مشتری عجله داره، تو ورد گیر کردی',
    ],
    benefits: [
      { icon: FileText, title: 'قالب اجاره‌نامه', desc: 'فیلدهای کامل' },
      { icon: Users, title: 'طرفین از CRM', desc: 'شماره و آدرس درست' },
      { icon: Calendar, title: 'تاریخ شمسی', desc: 'شروع و پایان' },
      { icon: Wallet, title: 'وصل به مالی', desc: 'رهن و اجاره ثبت' },
    ],
    steps: [
      { title: 'ملک اجاره‌ای', desc: 'توی فایلینگ' },
      { title: 'اجاره‌نامه', desc: 'پر کن و PDF' },
      { title: 'تحویل مشتری', desc: 'چاپ یا PDF' },
    ],
    faq: [
      { q: 'تمدید هم؟', a: 'آره — از روی قرارداد قبلی کپی سریع.' },
    ],
    ctaTitle: 'اجاره‌نامه رو سریع بزن',
    ctaSubtitle: '۴۸ ساعت رایگان',
    relatedSlugs: ['mubayaeh-amlak', 'filing-amlak'],
  },
  {
    slug: 'filing-software-amlak',
    keyword: 'نرم افزار فایلینگ املاک',
    title: 'نرم افزار فایلینگ املاک ابری — پوشه',
    metaDescription: 'نرم افزار فایلینگ املاک کامل: ثبت، جستجو، QR، اشتراک و تور مجازی.',
    keywords: 'نرم افزار فایلینگ املاک, فایلینگ املاک, پوشه',
    heroBadge: 'همه‌فن‌حریف',
    heroTitle: 'نرم افزار فایلینگ املاک که بعدش CRM و حسابداری هم داره',
    heroSubtitle: 'یک نرم‌افزار، نه پنج ابزار جدا. فایلینگ از همینجا شروع می‌شه.',
    heroImage: IMG.filing,
    accent: 'from-green-500 to-emerald-600',
    glow: 'bg-green-500/20',
    painTitle: 'چند نرم‌افزار داری؟',
    painPoints: [
      'فایلینگ یکی، CRM یکی، قرارداد یکی',
      'داده sync نمی‌شه',
      'هزینه اشتراک چندتا',
      'آموزش برای هر کدوم',
    ],
    benefits: [
      { icon: Building2, title: 'فایلینگ حرفه‌ای', desc: 'هسته پوشه' },
      { icon: Kanban, title: '+ CRM', desc: 'همون داده' },
      { icon: Calculator, title: '+ حسابداری', desc: 'همون معامله' },
      { icon: Camera, title: '+ تور مجازی', desc: 'همون ملک' },
    ],
    steps: [
      { title: 'ثبت‌نام', desc: 'یک اکانت' },
      { title: 'فایل بزن', desc: 'همه ماژول‌ها باز' },
      { title: 'رشد کن', desc: 'پلن بالا ببر' },
    ],
    faq: [
      { q: 'فقط فایلینگ می‌خوام', a: 'پلن solo شروع کن — بعد اضافه کن.' },
    ],
    ctaTitle: 'نرم‌افزار یکجا بگیر',
    ctaSubtitle: 'پوشه — ۴۸ ساعت رایگان',
    relatedSlugs: ['filing-amlak', 'posheh-software'],
  },
  {
    slug: 'construction-partnership',
    keyword: 'مشارکت در ساخت',
    title: 'مشارکت در ساخت — مدیریت فایل و قرارداد در پوشه',
    metaDescription: 'مشارکت در ساخت: فایل پروژه، قرارداد، مشتری و گزارش در یک پنل.',
    keywords: 'مشارکت در ساخت, پروژه ساختمانی, پوشه',
    heroBadge: 'پروژه‌ای هم بلده',
    heroTitle: 'مشارکت در ساخت — فایل پروژه قاطی نشه',
    heroSubtitle: 'واحدها، سهم‌ها، قرارداد مشارکت — برای دفاتری که پروژه هم می‌زنن.',
    heroImage: IMG.office,
    accent: 'from-orange-500 to-amber-600',
    glow: 'bg-orange-500/20',
    painTitle: 'پروژه ≠ آپارتمان آماده',
    painPoints: [
      'چند واحد، چند مالک — اکسل جهنم',
      'قرارداد مشارکت طولانی و خاص',
      'مشتری می‌پرسه «چندم طبقه؟» — جواب سریع نداری',
      'عکس پروژه پراکنده',
    ],
    benefits: [
      { icon: Building2, title: 'فایل پروژه', desc: 'طبقه، واحد، وضعیت' },
      { icon: FileText, title: 'قرارداد مشارکت', desc: 'قالب و PDF' },
      { icon: BarChart3, title: 'گزارش فروش واحد', desc: 'کدوم رفت، کدوم موند' },
      { icon: Camera, title: 'تور پروژه', desc: 'پیشرفت ساخت مجازی' },
    ],
    steps: [
      { title: 'پروژه ثبت', desc: 'به عنوان فایل خاص' },
      { title: 'واحدها', desc: 'لیست و قیمت' },
      { title: 'فروش و قرارداد', desc: 'همون CRM' },
    ],
    faq: [
      { q: 'فقط مسکونی آماده؟', a: 'نه — پروژه و مشارکت هم پوشش داده می‌شه.' },
    ],
    ctaTitle: 'پروژه رو منظم کن',
    ctaSubtitle: 'رایگان امتحان کن',
    relatedSlugs: ['filing-amlak', 'mubayaeh-amlak'],
  },
  {
    slug: 'posheh-assistant',
    keyword: 'دستیار املاک پوشه',
    title: 'دستیار املاک پوشه — همه‌کاره دفتر شما',
    metaDescription: 'دستیار املاک پوشه: فایلینگ، CRM، قرارداد، تور مجازی و ربات — یک دستیار دیجیتال.',
    keywords: 'دستیار املاک پوشه, پوشه, نرم افزار املاک',
    heroBadge: 'دستیار ۲۴/۷',
    heroTitle: 'دستیار املاک پوشه — مثل منشی که همه‌چیز رو یادشه',
    heroSubtitle: 'یادآور بازدید، کپی آگهی، Match مشتری، ربات تلگرام — کارهای تکراری رو بسپر به پوشه.',
    heroImage: IMG.brand,
    accent: 'from-primary to-accent',
    glow: 'bg-primary/20',
    painTitle: 'منشی نیستی، مشاوری',
    painPoints: [
      'نیمی از وقت administrative است',
      'یادآوری بازدید دستی',
      'جواب تلگرام مشتری تا شب',
      'آگهی برای دیوار دستی',
    ],
    benefits: [
      { icon: Bot, title: 'ربات تلگرام/واتساپ', desc: 'پاسخ اول خودکار' },
      { icon: Sparkles, title: 'کپی آگهی AI', desc: 'متن آماده انتشار' },
      { icon: Zap, title: 'Match خودکار', desc: 'ملک برای مشتری' },
      { icon: Smartphone, title: 'یادآور SMS', desc: 'بازدید فراموش نشه' },
    ],
    steps: [
      { title: 'پوشه رو روشن کن', desc: 'ثبت‌نام' },
      { title: 'ربات وصل کن', desc: 'تلگرام دفتر' },
      { title: 'سبک کار عوض شه', desc: 'تمرکز روی فروش' },
    ],
    faq: [
      { q: 'جای مشاور می‌شه؟', a: 'نه — کمک‌کنه. فروش هنوز با توئه.' },
    ],
    ctaTitle: 'دستیارت رو فعال کن',
    ctaSubtitle: '۴۸ ساعت رایگان',
    relatedSlugs: ['posheh', 'posheh-software'],
  },
  {
    slug: 'posheh-software',
    keyword: 'نرم افزار املاک پوشه',
    title: 'نرم افزار املاک پوشه — پلتفرم کامل دفتر',
    metaDescription: 'نرم افزار املاک پوشه: فایلینگ، CRM، حسابداری، قرارداد، تور مجازی و سایت دفتر.',
    keywords: 'نرم افزار املاک پوشه, پوشه, سامانه املاک',
    heroBadge: 'پلتفرم کامل',
    heroTitle: 'نرم افزار املاک پوشه — یکجا، نه قاطی‌پاتی',
    heroSubtitle: 'از ثبت فایل تا قرارداد و تور مجازی. برای دفترهایی که می‌خوان حرفه‌ای باشن، نه فقط «نرم‌افزار داشته باشن».',
    heroImage: IMG.brand,
    accent: 'from-teal-400 to-primary',
    glow: 'bg-primary/25',
    painTitle: 'چرا پوشه؟',
    painPoints: [
      'ابزار ایرانی که زبان دفتر رو بفهمه',
      'پشتیبانی واقعی — نه تیکت بی‌جواب',
      'قیمت شفاف — بدون هزینه پنهان',
      'آپدیت مداوم — تور مجازی، ربات، KPI',
    ],
    benefits: [
      { icon: Building2, title: 'فایلینگ', desc: 'هسته' },
      { icon: Kanban, title: 'CRM', desc: 'فروش' },
      { icon: Calculator, title: 'حسابداری', desc: 'مالی' },
      { icon: Camera, title: 'تور مجازی', desc: 'بازاریابی' },
      { icon: Globe, title: 'سایت دفتر', desc: 'برند' },
      { icon: Shield, title: 'امنیت', desc: 'داده جدا' },
    ],
    steps: [
      { title: '۴۸ ساعت رایگان', desc: 'بدون کارت' },
      { title: 'تیم رو دعوت کن', desc: 'مشاورها' },
      { title: 'حرفه‌ای شو', desc: 'پلن مناسب' },
    ],
    faq: [
      { q: 'با رقبا چطوره؟', a: 'یکجا بودن ماژول‌ها + تور مجازی + پشتیبانی ایرانی.' },
    ],
    ctaTitle: 'پوشه رو همین الان بزن',
    ctaSubtitle: 'ثبت‌نام ۲ دقیقه — شروع ۴۸ ساعت رایگان',
    relatedSlugs: ['posheh', 'filing-amlak', 'virtual-tour-amlak'],
  },
  {
    slug: 'posheh',
    keyword: 'پوشه',
    title: 'پوشه — نرم‌افزار املاک برای مشاوران ایران',
    metaDescription: 'پوشه: سامانه ابری فایلینگ، CRM و تور مجازی املاک. خودمونی، سریع، ایرانی.',
    keywords: 'پوشه, نرم افزار املاک پوشه, دستیار املاک پوشه',
    heroBadge: 'خوش اومدی',
    heroTitle: 'پوشه — وقتی دفتر املاک می‌خواد جدی بازی کنه',
    heroSubtitle: 'ما مشاورها رو می‌شناسیم. پوشه از دل همون کار درومده — نه از ترجمه یه نرم‌افزار خارجی.',
    heroImage: IMG.brand,
    accent: 'from-primary via-accent to-teal-500',
    glow: 'bg-primary/30',
    painTitle: 'داستان پوشه',
    painPoints: [
      'اکسل و واتساپ جواب نمی‌دن وقتی دفتر رشد کنه',
      'مشتری انتظار آنلاین داره — تو هنوز PDF می‌فرستی',
      'مدیر نمی‌دونه امروز کی چقدر فروخته',
      'می‌خوای حرفه‌ای باشی بدون تیم IT',
    ],
    benefits: [
      { icon: Sparkles, title: 'ساده و خودمونی', desc: 'نه کتابی و سخت' },
      { icon: Cloud, title: 'ابری', desc: 'هر جا کار کن' },
      { icon: Users, title: 'تیم', desc: 'مشاور تا مدیر' },
      { icon: Headphones, title: 'پشتیبانی', desc: 'ایرانی، واقعی' },
    ],
    steps: [
      { title: 'ثبت‌نام', desc: 'ایمیل + رمز' },
      { title: '۳ دقیقه راه‌اندازی', desc: 'پنل آماده' },
      { title: 'فروش', desc: 'بقیه با ماست' },
    ],
    faq: [
      { q: 'پوشه چیه خلاصه؟', a: 'نرم‌افزار یکجا برای دفتر املاک — فایلینگ تا تور مجازی.' },
      { q: 'رایگان؟', a: '۴۸ ساعت کامل رایگان — بعد پلن انتخاب می‌کنی.' },
    ],
    ctaTitle: 'بزن بریم — ثبت‌نام رایگان',
    ctaSubtitle: 'همین الان ۴۸ ساعت تست کامل',
    relatedSlugs: ['posheh-software', 'filing-amlak', 'crm-amlak'],
  },
  {
    slug: 'virtual-visit-amlak',
    keyword: 'بازدید مجازی املاک',
    title: 'بازدید مجازی املاک — کمتر راه بیا، بیشتر بفروش',
    metaDescription: 'بازدید مجازی املاک با تور ۳۶۰ پوشه. مشتری از راه دور ببینه، تو وقتت رو جدی بگیر.',
    keywords: 'بازدید مجازی املاک, املاک مجازی, پوشه',
    heroBadge: 'بازدید هوشمند',
    heroTitle: 'بازدید مجازی املاک — اول آنلاین، بعد حضوری',
    heroSubtitle: 'مشتری serious رو تشخیص بده. بقیه اول تور ببینن، بعد بیان.',
    heroImage: IMG.tour,
    accent: 'from-cyan-400 to-teal-600',
    glow: 'bg-cyan-500/20',
    painTitle: 'بازدید حضوری همه؟',
    painPoints: [
      'روز تعطیل ۵ بازدید — ۴ بی‌خرید',
      'مسافت دور — مشتری نمی‌آد',
      'COVID یادمون نره — آنلاین عادی شد',
      'رقبا لینک تور می‌دن',
    ],
    benefits: [
      { icon: Camera, title: 'تور قبل بازدید', desc: 'فیلتر مشتری' },
      { icon: Globe, title: 'لینک یکتا', desc: 'هر فایل' },
      { icon: BarChart3, title: 'ببین کی دید', desc: 'آنالیتیکس' },
      { icon: Smartphone, title: 'موبایل‌فرند', desc: 'اندروید و iOS' },
    ],
    steps: [
      { title: 'تور بساز', desc: '۵ دقیقه' },
      { title: 'بفرست', desc: 'قبل بازدید حضوری' },
      { title: 'بازدید جدی', desc: 'وقتت حفظ می‌شه' },
    ],
    faq: [
      { q: 'جای بازدید حضوری می‌شه؟', a: 'نه — ولی ۸۰٪ سوال قبلش جواب می‌گیره.' },
    ],
    ctaTitle: 'بازدید مجازی رو شروع کن',
    ctaSubtitle: 'رایگان — پوشه',
    relatedSlugs: ['virtual-tour-amlak', 'virtual-real-estate'],
  },
  {
    slug: 'virtual-real-estate',
    keyword: 'املاک مجازی',
    title: 'املاک مجازی — نمایش حرفه‌ای فایل‌ها',
    metaDescription: 'املاک مجازی با تور ۳۶۰ و سایت دفتر. برندت آنلاین قوی باشه.',
    keywords: 'املاک مجازی, تور مجازی, پوشه',
    heroBadge: 'برند آنلاین',
    heroTitle: 'املاک مجازی — دفترت ۲۴ ساعت بازه',
    heroSubtitle: 'حتی وقتی خوابی، مشتری تور می‌بینه، فرم می‌ده، تماس می‌گیره.',
    heroImage: IMG.tour,
    accent: 'from-purple-500 to-pink-600',
    glow: 'bg-purple-500/20',
    painTitle: 'فقط فیزیکی؟',
    painPoints: [
      'ساعت ۱۱ شب مشتری می‌خواد ببینه',
      'سایت دفتر خالیه یا قدیمی',
      'فقط دیوار — برند خودت نیست',
      'تور نداری = حرفه‌ای نیست',
    ],
    benefits: [
      { icon: Globe, title: 'سایت اختصاصی', desc: 'URL دفتر' },
      { icon: Camera, title: 'تور هر فایل', desc: 'مجازی واقعی' },
      { icon: QrCode, title: 'QR روی بروشور', desc: 'چاپ و آنلاین' },
      { icon: Sparkles, title: 'فرم سرنخ', desc: 'جمع‌آوری مشتری' },
    ],
    steps: [
      { title: 'سایت دفتر', desc: 'فعال کن' },
      { title: 'تورها', desc: 'روی فایل‌ها' },
      { title: 'مشتری آنلاین', desc: '۲۴/۷' },
    ],
    faq: [
      { q: 'سایت جدا می‌خواد؟', a: 'توی پلن حرفه‌ای — همه یکجا.' },
    ],
    ctaTitle: 'املاک مجازی رو بساز',
    ctaSubtitle: '۴۸ ساعت رایگان',
    relatedSlugs: ['virtual-tour-amlak', 'posheh-software'],
  },
  {
    slug: 'virtual-property-visit',
    keyword: 'بازدید ملک مجازی',
    title: 'بازدید ملک مجازی — یک لینک، کل ملک',
    metaDescription: 'بازدید ملک مجازی: تور ۳۶۰ و اسمارت‌واک برای هر ملک در پوشه.',
    keywords: 'بازدید ملک مجازی, تور مجازی ملک, پوشه',
    heroBadge: 'یک لینک کافیه',
    heroTitle: 'بازدید ملک مجازی — مشتری اتاق‌ها رو قدم‌به‌قدم ببینه',
    heroSubtitle: 'نه ۲۰ عکس شلوغ — یک تور تمیز با فلش و موزیک.',
    heroImage: IMG.tour,
    accent: 'from-lime-500 to-green-600',
    glow: 'bg-lime-500/20',
    painTitle: 'عکس گالری کافی نیست',
    painPoints: [
      'مشتری گیج — کدوم عکس پذیراییه؟',
      'فضا رو درک نمی‌کنه',
      'می‌پرسه «می‌شه ویدیو؟» — نداری',
      'لینک تور رقیب حرفه‌ای‌تره',
    ],
    benefits: [
      { icon: Camera, title: 'اسمارت‌واک', desc: 'حرکت بین نقاط' },
      { icon: Sparkles, title: 'موزیک تور', desc: 'حس لوکس' },
      { icon: MapPin, title: 'چند صحنه', desc: 'همه فضاها' },
      { icon: FileText, title: 'کنار فایل', desc: 'قیمت و مشخصات' },
    ],
    steps: [
      { title: 'عکس بگیر', desc: 'گوشی کافیه' },
      { title: 'تور بساز', desc: 'توی پوشه' },
      { title: 'لینک بده', desc: 'بازدید مجازی' },
    ],
    faq: [
      { q: 'کیفیت عکس موبایل اوکیه؟', a: 'برای شروع آره — بعد می‌تونی حرفه‌ای ارتقا بدی.' },
    ],
    ctaTitle: 'بازدید مجازی ملک رو بزن',
    ctaSubtitle: 'رایگان شروع کن',
    relatedSlugs: ['virtual-tour-property', 'virtual-tour-amlak'],
  },
]

export function getLandingBySlug(slug: string): KeywordLandingConfig | undefined {
  return KEYWORD_LANDINGS.find((l) => l.slug === slug)
}

export function landingPath(slug: string): string {
  return `/r/${slug}`
}

export const LANDING_SLUGS = KEYWORD_LANDINGS.map((l) => l.slug)
