/** کاتالوگ ۵۲+ قابلیت پنل مدیریت پلتفرم — مرجع docs/SUPER-ADMIN-PROMPT.md */
export const ADMIN_CAPABILITIES = [
  { id: 1, group: 'نمای کلی', name: 'داشبورد KPI', route: '/' },
  { id: 2, group: 'نمای کلی', name: 'گزارش‌ها و نمودار', route: '/reports' },
  { id: 3, group: 'نمای کلی', name: 'تحلیل‌های پلتفرم', route: '/analytics' },
  { id: 4, group: 'نمای کلی', name: 'درآمد و MRR', route: '/revenue' },
  { id: 5, group: 'نمای کلی', name: 'جستجوی سراسری', route: '/' },
  { id: 6, group: 'نمای کلی', name: 'دفاتر در معرض ریزش', route: '/churn' },
  { id: 7, group: 'دفاتر', name: 'لیست دفاتر', route: '/tenants' },
  { id: 8, group: 'دفاتر', name: 'جزئیات دفتر', route: '/tenants/:id' },
  { id: 9, group: 'دفاتر', name: 'فعال/غیرفعال دفتر', route: '/tenants/:id' },
  { id: 10, group: 'دفاتر', name: 'مدیری trial', route: '/tenants/:id' },
  { id: 11, group: 'دفاتر', name: 'تأیید وبسایت', route: '/tenants' },
  { id: 12, group: 'دفاتر', name: 'تخصیص پلن', route: '/tenants/:id' },
  { id: 13, group: 'کاربران', name: 'لیست کاربران', route: '/users' },
  { id: 14, group: 'کاربران', name: 'جزئیات کاربر', route: '/users/:id' },
  { id: 15, group: 'کاربران', name: 'ویرایش نقش', route: '/users/:id' },
  { id: 16, group: 'کاربران', name: 'خروج همه دستگاه‌ها', route: '/users' },
  { id: 17, group: 'کاربران', name: 'Impersonate', route: '/users' },
  { id: 18, group: 'کاربران', name: 'مدیران پلتفرم', route: '/staff' },
  { id: 19, group: 'کاربران', name: 'افزودن مدیر', route: '/staff' },
  { id: 20, group: 'کاربران', name: 'دستگاه‌ها', route: '/devices' },
  { id: 21, group: 'کاربران', name: 'لاگ impersonation', route: '/impersonation' },
  { id: 22, group: 'داده', name: 'لیست مشتریان', route: '/customers' },
  { id: 23, group: 'داده', name: 'لیست مالکان', route: '/owners' },
  { id: 24, group: 'داده', name: 'املاک سراسری', route: '/properties' },
  { id: 25, group: 'داده', name: 'CRM معاملات', route: '/crm' },
  { id: 26, group: 'داده', name: 'بازدیدهای ملک', route: '/visits' },
  { id: 27, group: 'داده', name: 'درخواست بازدید سایت', route: '/visits' },
  { id: 28, group: 'داده', name: 'قراردادها', route: '/contracts' },
  { id: 29, group: 'مالی', name: 'اشتراک‌ها', route: '/subscriptions' },
  { id: 30, group: 'مالی', name: 'تمدید اشتراک', route: '/subscriptions' },
  { id: 31, group: 'مالی', name: 'پلن‌ها CRUD', route: '/plans' },
  { id: 32, group: 'مالی', name: 'پرداخت‌ها', route: '/payments' },
  { id: 33, group: 'مالی', name: 'کیف پول', route: '/wallets' },
  { id: 34, group: 'مالی', name: 'تراکنش کیف پول', route: '/wallet-transactions' },
  { id: 35, group: 'مالی', name: 'کوپن‌ها', route: '/coupons' },
  { id: 36, group: 'مالی', name: 'کمیسیون‌ها', route: '/commissions' },
  { id: 37, group: 'مالی', name: 'حسابداری', route: '/accounting' },
  { id: 38, group: 'مالی', name: 'Export کاربران', route: '/exports' },
  { id: 39, group: 'مالی', name: 'Export پرداخت‌ها', route: '/exports' },
  { id: 40, group: 'پشتیبانی', name: 'تیکت‌ها', route: '/tickets' },
  { id: 41, group: 'پشتیبانی', name: 'اطلاعیه‌ها', route: '/announcements' },
  { id: 42, group: 'پشتیبانی', name: 'وبلاگ', route: '/blog' },
  { id: 43, group: 'پشتیبانی', name: 'دانلود اپ', route: '/downloads' },
  { id: 44, group: 'سیستم', name: 'تنظیمات', route: '/settings' },
  { id: 45, group: 'سیستم', name: 'Feature flags', route: '/system' },
  { id: 46, group: 'سیستم', name: 'حالت تعمیرات', route: '/system' },
  { id: 47, group: 'سیستم', name: 'لاگ ممیزی', route: '/audit' },
  { id: 48, group: 'سیستم', name: 'وضعیت SMS', route: '/settings' },
  { id: 49, group: 'سیستم', name: 'کافه‌بازار', route: '/settings' },
  { id: 50, group: 'سیستم', name: 'Export دفاتر', route: '/exports' },
  { id: 51, group: 'سیستم', name: 'Export مشتریان', route: '/exports' },
  { id: 52, group: 'سیستم', name: 'سلامت سیستم', route: '/system' },
] as const

export const CAPABILITY_COUNT = ADMIN_CAPABILITIES.length
