export const PROPERTY_OPTIONS = {
  types: [
    { value: 'sale', label: 'فروش' },
    { value: 'rent', label: 'اجاره' },
    { value: 'mortgage', label: 'رهن' },
    { value: 'pre_sale', label: 'پیش‌فروش' },
    { value: 'land', label: 'زمین' },
    { value: 'garden', label: 'باغ' },
    { value: 'commercial', label: 'تجاری' },
    { value: 'warehouse', label: 'انبار' },
    { value: 'partnership', label: 'مشارکت' },
  ],
  buildingTypes: [
    { value: 'apartment', label: 'آپارتمان' },
    { value: 'villa', label: 'ویلایی' },
    { value: 'penthouse', label: 'پنت‌هاوس' },
    { value: 'shop', label: 'مغازه' },
    { value: 'office', label: 'دفتر' },
    { value: 'suite', label: 'سوئیت' },
  ],
  deedTypes: [
    { value: 'single_deed', label: 'تک‌برگ' },
    { value: 'contract', label: 'قولنامه' },
    { value: 'shared', label: 'مشاع' },
    { value: 'power_of_attorney', label: 'وکالتی' },
  ],
  directions: [
    { value: 'north', label: 'شمالی' },
    { value: 'south', label: 'جنوبی' },
    { value: 'east', label: 'شرقی' },
    { value: 'west', label: 'غربی' },
  ],
  permissions: [
    { value: 'office', label: 'دفتری' },
    { value: 'team', label: 'تیمی' },
    { value: 'private', label: 'خصوصی' },
    { value: 'manager_only', label: 'فقط مدیر' },
  ],
  sources: [
    { value: 'owner_direct', label: 'مالک مستقیم' },
    { value: 'colleague', label: 'همکار' },
    { value: 'divar', label: 'دیوار' },
    { value: 'website', label: 'وب‌سایت' },
    { value: 'walk_in', label: 'مراجعه حضوری' },
  ],
  renovationStatuses: [
    { value: 'new', label: 'نوساز' },
    { value: 'renovated', label: 'بازسازی‌شده' },
    { value: 'old', label: 'قدیمی' },
    { value: 'needs_renovation', label: 'نیاز به بازسازی' },
  ],
  amenities: [
    { value: 'balcony', label: 'بالکن' },
    { value: 'pool', label: 'استخر' },
    { value: 'sauna', label: 'سونا' },
    { value: 'jacuzzi', label: 'جکوزی' },
    { value: 'security', label: 'نگهبانی' },
    { value: 'cctv', label: 'دوربین' },
    { value: 'lobby', label: 'لابی' },
    { value: 'gym', label: 'سالن ورزش' },
    { value: 'furnished', label: 'مبله' },
    { value: 'open_kitchen', label: 'آشپزخانه اوپن' },
  ],
}
